---
- name: Create empty file
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Creating an empty file
    file:
     path: "./output_files/{{filename}}"
     state: touch

- name: Use tmsh commands
  hosts: f5
  connection: local
  gather_facts: false
  serial: 1

  tasks:

  - name: Run the listed tmsh commands
    bigip_command:
     provider:
      server: "{{server}}"
      user: "{{user}}"
      password: "{{password}}"
      server_port: "{{server_port}}"
      validate_certs: "{{validate_certs}}"
     commands:
      - create ltm node 10.10.100.60
    register: result

  - lineinfile:
     line: "\n###BIG-IP hostname => {{ inventory_hostname }} ###\n"
     insertafter: EOF
     dest: "./output_files/{{filename}}"

  - lineinfile:
     line: "{{ result.stdout_lines }}"
     insertafter: EOF
     dest: "./output_files/{{filename}}"

  - name: Format the file
    shell:
     cmd: sed 's/,/\n/g' ./output_files/{{filename}} > ./output_files/{{filename}}_formatted

  - pause:
     seconds: 10

- name: Delete file
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Delete extra file created (delete file)
    file:
     path: ./output_files/{{filename}}
     state: absent